apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: take-on
  name: business-layer
  labels:
    app: business-layer
spec:
  replicas: 1
  template:
    metadata:
      namespace: take-on
      labels:
        app: business-layer
    spec:
      containers:
        - name: business-layer
          image: 014669633018.dkr.ecr.eu-west-2.amazonaws.com/take-on-bl
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8090
              protocol: TCP
      imagePullSecrets:
        - name: aws-ecr
